### ISSUE TITLE
(obv.lib::download-lib) fails ?

### ISSUE THREAD

**Issue by lispm** [thicksteadTHpp/Obvius#10]
macOS 10.15.3 & sbcl 2.0.2

```
CL-USER> (obv.lib::download-lib)
..Try to download precompiled library for osx 
...from: https://github.com/thicksteadTHpp/Obvius/releases/download/v3.2.1/libobvius.dylib.-x86_64-osx-v3.2.1 Downloading "https://github.com/thicksteadTHpp/Obvius/releases/download/v3.2.1/libobvius.dylib.-x86_64-osx-v3.2.1" (Unknown size)
[md5] checking file integrity: /Users/foo/.cache/common-lisp/sbcl-2.0.2-macosx-x64/Users/foo/quicklisp/local-projects/obvious/bin/libobvius.dylib
[md5] integrity check: NIL[download] delete (probably) compromised file: /Users/foo/.cache/common-lisp/sbcl-2.0.2-macosx-x64/Users/foo/quicklisp/local-projects/obvious/bin/libobvius.dylib
NIL
```

**Comment by thicksteadTHpp** [comment]
i will check that

**Comment by thicksteadTHpp** [comment]
Linux output:
[package obv.lib]...Try to download precompiled library for linux 
...from: https://github.com/thicksteadTHpp/Obvius/releases/download/v3.2.1/libobvius.so.-x86_64-linux-v3.2.1 ...Downloading "https://github.com/thicksteadTHpp/Obvius/releases/download/v3.2.1/libobvius.so.-x86_64-linux-v3.2.1" (Unknown size)
.
[md5] checking file integrity: /home/tobias/.cache/common-lisp/sbcl-2.0.1-linux-x64/home/tobias/emacs/github/obvius/obvius31/bin/libobvius.so
[md5] integrity check: T
[lib]..successfully downloaded precompiled lib to /home/tobias/.cache/common-lisp/sbcl-2.0.1-linux-x64/home/tobias/emacs/github/obvius/obvius31/bin/libobvius.so

**Comment by thicksteadTHpp** [comment]
i will recreate the digest for MacOS

**Comment by thicksteadTHpp** [comment]
please pull in the current master branch. or use 
```
(in-package :obv.lib)

(defparameter *file-digest*
#+(and darwin x86-64) #(192 178 18 221 63 147 5 127 25 154 174 207 91 92 203 110))

```

**Comment by lispm** [comment]
That worked. Then had to install libtiff manually.

**Comment by thicksteadTHpp** [comment]
this libtiff is a problem ....

**Comment by lispm** [comment]
Just a hint, note that you need to quote code blocks examples with backquotes.

`
(defparameter *foo* bar)
`

Otherwise it would treat Lisp code as markup, which makes it difficult to understand it for the reader. I know that it's not *file-digest*, but `*file-digest*`, but some people might miss that...
