### ISSUE TITLE
Darwin

### ISSUE THREAD

**Issue by lispm** [thicksteadTHpp/Obvius#9]
Something like

```
(defparameter *foo* 
  #+(and unix bar) "aa"
  #+(and darwin bar) "bb")
```

Will not work as intended, since DARWIN is also a UNIX. Thus both forms will be read.

Any use of DARWIN in conditional readers would need to be checked.

Better

```
(defparameter *foo* 
  #+(and unix (not darwin) bar) "aa"
  #+(and darwin bar) "bb")
```

**Comment by thicksteadTHpp** [comment]
Thanks a lot. Since i don't have a mac to test it - this is very appreciated.  i will work it in.

**Comment by thicksteadTHpp** [comment]
...a mac
